version: 2
services:
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      MARIADB_USER: 'suitecrm_user'
      MARIADB_DATABASE: 'suitecrm_db'
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mariadb_data:/bitnami
  suitecrm:
    image: bitnami/suitecrm:latest
    environment:
      MARIADB_HOST: 'mariadb'
      MARIADB_PORT_NUMBER: '3306'
      SUITECRM_DATABASE_USER: 'suitecrm_user'
      SUITECRM_DATABASE_NAME: 'suitecrm_db'
      ALLOW_EMPTY_PASSWORD: 'yes'
      SUITECRM_USERNAME: '${username}'
      SUITECRM_PASSWORD: '${password}'
      SUITECRM_EMAIL: '${email}'
    labels:
      kompose.service.type: nodeport
    ports:
      - '${port}:80'
    volumes:
      - suitecrm_data:/bitnami
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local