.catalog:
  name: "Alfresco"
  version: "5.1.0-201605-GA"
  description: "Alfresco Electronic Document Management"
  uuid: alfresco-5.1-201605-1
  minimum_rancher_version: v0.56.0
  questions:
    - variable: database_name
      description: "Name of the Alfresco database"
      label: "Database name"
      type: "string"
      required: true
      default: "alfresco"
    - variable: database_user
      description: "Login for the Alfresco database"
      label: "Database login"
      type: "string"
      required: true
      default: "alfresco"
    - variable: database_password
      description: "Password for the Alfresco database"
      label: "Database password"
      type: "string"
      required: true
      default: "alfresco"
